server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: circuitBreakerUserService
                fallbackUri: forward:/fallback/users

        - id: notification
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      circuitBreakerUserService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
