server:
  port: 8081

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: diradd23@gmail.com
    password: olzt qdmf cslv dzen
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: host.docker.internal:9092
    topic:
      user: user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
